Move panel to tool shelf
oli414/Blender-RCT-Graphics pull request #23
Opened 2022-12-17 05:04 UTC by spacek531

This un-buries the RCT helpers panel from the render properties panel and puts it in the "tool shelf" where it is easier to access.

2022-12-17 15:21 UTC, oli414 commented
Nice, I like that.

I don't want to mention the name of the original game in full, can you make the title "RCT Graphics" instead

2022-12-17 19:33 UTC, spacek531 commented
I was planning to add my own plugin in the same tab so how about RCT tools?

2023-03-03 20:11 UTC, spacek531 commented
Anything stopping this PR from merging?

2023-03-03 21:25 UTC, oli414 commented
Hadn't had the chance to check it out myself yet

2023-03-03 21:26 UTC, oli414 requested changes

2023-03-03 21:26 UTC, oli414 commented on rct-graphics-helper/rct_graphics_helper_panel.py
> +    bl_category = 'RCT'
Lets call it RCT Tools then as per your suggestion

2023-03-03 22:15 UTC, oli414 commented
Can you update the readme accordingly btw?

2023-03-04 16:07 UTC, merged